---
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: webfamilygallery
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: REGISTRY_URL/web-family-gallery/webfamilygallery:BUILD_NUMBER
          ports:
            - containerPort: 3000
